apiVersion: v1
kind: ConfigMap
metadata:
  name: rails-app-config
  namespace: ror-app
data:
  RAILS_ENV: "production"
  RDS_DB_NAME: "ror_app_production"
  RDS_HOSTNAME: "ror-app-db.cs9u4m2q2o9n.us-east-1.rds.amazonaws.com"
  RDS_PORT: "5432"
  S3_BUCKET_NAME: "ror-app-storage-c25641d9"
  S3_REGION_NAME: "us-east-1"
  LB_ENDPOINT: "PENDING"